find_package(PkgConfig)

pkg_check_modules(GTK3 gtk+-3.0>=3.22.9)

if (GTK3_FOUND)
    SET(GTK3_LIBRARY_DIRS ${GTK3_LIBDIR})
    SET(GTK3_LIBRARIES ${GTK3_LDFLAGS})
    SET(GTK3_C_FLAGS ${GTK3_CFLAGS})
    if (NOT Gtk3_FIND_QUIETLY)
        message(STATUS "Found Gtk3")
    endif ()
else ()
    if (NOT Gtk3_FIND_QUIETLY)
        if (Gtk3_FIND_REQUIRED)
            message(FATAL_ERROR "Could not find Gtk3")
        else ()
            message(STATUS "Could not find Gtk3")
        endif ()
    endif ()
endif ()
