find_package(PkgConfig)

pkg_check_modules(WEBKIT2GTK webkit2gtk-4.0>=2.14.5)

if (WEBKIT2GTK_FOUND)
    if (NOT WebKit2Gtk_FIND_QUIETLY)
        message(STATUS "Found WebKit2Gtk")
    endif ()
    SET(WEBKIT2GTK_LIBRARY_DIRS ${WEBKIT2GTK_LIBDIR})
    SET(WEBKIT2GTK_LIBRARIES ${WEBKIT2GTK_LDFLAGS})
    SET(WEBKIT2GTK_C_FLAGS ${WEBKIT2GTK_CFLAGS})
else ()
    if (NOT WebKit2Gtk_FIND_QUIETLY)
        if (WebKit2Gtk_FIND_REQUIRED)
            message(FATAL_ERROR "Could not find WebKit2Gtk")
        else ()
            message(STATUS "Could not find WebKit2Gtk")
        endif ()
    endif ()
endif ()
