find_package(PkgConfig)

pkg_check_modules(LIBNOTIFY libnotify>=0.7.7)

if (GTK3_FOUND)
    SET(LIBNOTIFY_LIBRARY_DIRS ${LIBNOTIFY_LIBDIR})
    SET(LIBNOTIFY_LIBRARIES ${LIBNOTIFY_LDFLAGS})
    SET(LIBNOTIFY_C_FLAGS ${LIBNOTIFY_CFLAGS})
    if (NOT LibNotify_FIND_QUIETLY)
        message(STATUS "Found LibNotify")
    endif ()
else ()
    if (NOT LibNotify_FIND_QUIETLY)
        if (LibNotify_FIND_REQUIRED)
            message(FATAL_ERROR "Could not find LibNotify")
        else ()
            message(STATUS "Could not find LibNotify")
        endif ()
    endif ()
endif ()
